package:
    name: cyordereddict
    version: 1.0.0

source:
    fn: cyordereddict-1.0.0.tar.gz
    url: https://pypi.python.org/packages/source/c/cyordereddict/cyordereddict-1.0.0.tar.gz
    md5: 8924331ec3bb754c92fd2603d3a29489

build:
    number: 1
    script: python setup.py install

requirements:
    build:
        - python
        - cython
    run:
        - python

test:
    imports:
        - cyordereddict
        - cyordereddict.benchmark
    commands:
        - conda inspect linkages -p ${PREFIX} cyordereddict  # [linux]

about:
    home: https://github.com/shoyer/cyordereddict
    license: MIT
    summary: Cython implementation of Python's collections.OrderedDict

extra:
    recipe-maintainers:
        - ocefpaf
        - jhamman
