appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nM3uy8v8SrQOfGHCCeJX9rhldCm/+0OcGPQTAdIEjF/lsin1CAQCGyN0aW0kHmx9cjQgqLy7W5mRdxq4O4pYfThEUG1JErKAXzgV7UHQLMcXn8VkIDr5P2flyjlgv4O6695r8VJCSSTZBGJDMF2hhHBpoVq+6g85NgFuSYcn0LS3BX5IOlao6A+k6FryIkUMnkzR5XPrr9c6XtLe/WGBwF5/JBqV5r43SJOGxo3WxvUuCF9UDnQz/95I20DfUog4fyyTDaO+dAnj47tBpLa6m7BJ3mt50qQh9zQyBGfMyuPKCgoipi9IkpMtwMlLkUqTU3zuy3nRbtBfKfESIl0jtu6CD5Y898uTp9h3Sv3X5xS8q2CaHcpR1Pes8JQSuO+a6NhG3bGhn/Wm8VUlQ8nIY8I0KQ5ueSEwWRrjAvNOvDJEnA8x9V0bdXA09e3FWfX1R348GnhvFXnrGqY2VP92BKpvzg1E3OnZ2unyfJuYNTTl0T+Kb6tPNnvZTkBFPUccQFaMRk+D3cuKyYAh89Cl11Oxvd6qHOaWpRIOKLRkquUacWqv28sdNc/AjOICp33G5RX/orBXJuZ8anTGePa6CGOcnHfNgr8/ES3rHxJ+kiCHlE7V2891PjMYtAdYfmhHginEQHRBuKR7YXtxUkgOEZYkyh9CvKOamCV9QyM4bdw=}
