travis:
  secure:
    BINSTAR_TOKEN: MeVzQggqpOP924XqrRv4tSblU4YUf/MotsjhUDX/6cc2aPTX3Wvm2bVxgAIQPNVpnBf4wmIv42ahvh5REG/drHc/cLgIkBkGDsb0u32MGJV3BXjwpDpqy3ulSRPGMmBpsR+cWQV8TXaWVsvClRIKpWXe6JfDq9y/6t7zBmzBfTZe8z534DZ7nUAfG+j+anNEaBaeZbi6Iw5sOUjmpOq+p/LAIIjqhjQSCMtYuB0fE8gAYO+CIHAaSYzBuUpspOSfD26/rduAdjitZv0NqLFQ9M0qy47CyqjxczkjIPjy6d7gpFxdJRnDumzoigifl0V9kmWzOq9a84THBsOE1cE/khCnElyw3n4HqNe/nNVeab6dhT1nlscfCkCKl1dyxXpJqcImoMxarhCfQ1LxpkNwFOy3oUWGh7bk5syQq2sI0dB6D8K7UKsXgWH0lcWX0whmaLXtpi4IMxM1qMFySwUYDWQksWA5EDt5mlYXFhQPeMDvC999TBsp0f7REP3VlmCejbQxj2C+x+wMkez2Y6vu/dfn8kzTmJG8dScLbeLtVwEFDkEHOxWFTRu1n/9e/JuZyxG9oDBGkSdoJxpYv2lS29NLcm0IBSeaCuDaGLsOo0/HIfFNehZTU+vvzJT74TTk+uSEVGvlhd5qDMicPcRSUiEChDbj0azO4r2pNUL+gZo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
